### ISSUE TITLE
Can't get the .exe or .js versions of SGOTT to run

### ISSUE THREAD

**Issue by Betrix5068** [zeddidragon/sgott#10]
What it says on the tin. I'm at my wits end trying to figure out what I'm doing wrong. Opening SGOTT.js gives me an 800A03F6 error, and SGOTT.exe just has a blank command prompt that doesn't do anything. I'm using windows 10 and don't think I'm doing anything unusual. Any help would be much appreciated.

**Comment by KCreator** [comment]
My main experience is with the exe version. Are you running the exe directly? If so, try running it via the command prompt with the arguments: "sgott.exe <target file> <output file>" instead. It's also worth remembering to specify extentions as well.

**Comment by Betrix5068** [comment]
Just ran it through a command prompt. The result was exactly the same as when I run it via double-clicking or right-click>open. This is with sgott.exe. To see if it works I've been entering -h into it (sgott) since the readme says that should work. Perhaps you could give me _exactly_ what I ought to type in? Either into sgott or comand prompt itself. There's always the possibility I'm doing something wrong on my end.

To clarify, wrote: cd [directory]>start sgott.exe

> represents pressing enter

For the record I'm a filthy GUI normie, so some of what you say might go over my head.

**Comment by KCreator** [comment]
Try (With ; representing enter): cd [directory];sgott.exe <sgofilename>.sgo <sgofilename>.json;

**Comment by Betrix5068** [comment]
damn, that worked! Thanks. Weird that the drag and drop doesn't work the same way.

**Comment by KCreator** [comment]
It's something that has been considered, but not implemented yet. Perhaps a future version will allow for that. I'm glad you where able to get it working.
