### ISSUE TITLE
modified some weapon value failed

### ISSUE THREAD

**Issue by sonying** [zeddidragon/sgott#2]
Based on EDFModLoader1.6.1
i tried to modify some weapon value like "ammodamage" but some customized failed.
Example ::
af-w.json  (success)
super-goliath (success)
_Weapon339_Mirage-15WR.json (failed)
_Weapon326_Mirage-5-Way.json (failed)
_Weapon656_ZE-GUN10.json (failed)
_Weapon485_YH7-Dispersal-Mortar.json (failed)

It seems that modifying characters other than the ranger will fail.

**Comment by KCreator** [comment]
Mind sending me the jsons? I will see if I can help debug.

**Comment by sonying** [comment]
example ::
1. open _Weapon339_Mirage-15WR.json
2. modify "AmmoDamage" to 90000
3. execute sgottstrap.exe

Enter the game and still display the original value

**Comment by KCreator** [comment]
Does the actual damage reflect ingame? The menu text uses pre-determined values that you have to edit in  meta{ "description" : "" }.

**Comment by sonying** [comment]
Seems useful, Thanks.

**Comment by zeddidragon** [comment]
This seems solved, I'm closing it.
