### ISSUE TITLE
Black Screen bug when installing Master for testing

### ISSUE THREAD

**Issue by FIRE-AKA-DRAZN** [zeddidragon/sgott#5]
Installing the most current release works fine.

After downloading the source files for testing and installing the mod, game displays a black screen and does not progress.  However the game's quit function still works (Alt F4) and correctly displays the menu and sounds.

This is probably due to an error with the weapon table or one of the scripts that reads/writes to it.

**Comment by KCreator** [comment]
I think its an issue with Mainscript.as not being properly included/copied over automaticaly with the default install. I think the mainscript is in the project, copy that to the root directory and try again, seeing if it works or not.

**Comment by FIRE-AKA-DRAZN** [comment]
I tried moving MAINSCRIPT.AS to the root EDF folder before performing the same install procedure.  Unfortunately I got the same bug again.

This is the Gitbash command i run to install the mod from the source:  `$ cp "c:/Users/F I R E/Desktop/EDF Mod Space/Project Source/sgott/sgottstrap/SgottTemplates/weapon"* "SgottTemplates/weapon/" && "c:/Users/F I R E/Desktop/EDF Mod Space/Project Source/sgott/sgottstrap/sgottstrap.js"`

i've attached some screenshots of my folder structure for the installation.
![root](https://user-images.githubusercontent.com/29803015/52556600-fd7afd00-2de4-11e9-9cd0-7881e565176c.png)
^root game folder

![mods](https://user-images.githubusercontent.com/29803015/52556625-0cfa4600-2de5-11e9-9436-5534f87dc100.png)
^game mod folder

![wepcount](https://user-images.githubusercontent.com/29803015/52556643-18e60800-2de5-11e9-9876-938625b07917.png)
^count of number of weapons copied over

![projecttempcount](https://user-images.githubusercontent.com/29803015/52556686-30bd8c00-2de5-11e9-8404-bd571966bb16.png)
^count of number of templates project worked with

![projectroot](https://user-images.githubusercontent.com/29803015/52556720-48951000-2de5-11e9-93cd-7d0bd624881f.png)
^root project folder

![sgottstrap](https://user-images.githubusercontent.com/29803015/52556731-521e7800-2de5-11e9-9646-87e2087523d6.png)
^project sgottstrap folder

**Comment by KCreator** [comment]
One more thing to check is to try copying commontypes.h to the sgottmods directory. I apologise that it did not automaticaly copy over.

**Comment by FIRE-AKA-DRAZN** [comment]
Ok, well we are making progress now, the game actually launches however it does 2 weird things now:

first i get a black screen with a blank message box and an OK button
![wut](https://user-images.githubusercontent.com/29803015/52559584-87c75f00-2ded-11e9-8e6c-1fd026a39a0e.png)

pressing enter or space advances to the normal intro screen where im told it cannot find my save game data
![wut2](https://user-images.githubusercontent.com/29803015/52559611-9c0b5c00-2ded-11e9-91b3-eaa8a9599d25.png)

I do actually have save data in the right place though that i've been using for testing
![saves](https://user-images.githubusercontent.com/29803015/52559633-b9402a80-2ded-11e9-8aba-2c3ece02d2e7.png)

Any idea why this happens?

**Comment by KCreator** [comment]
I can confirm the empty message is mostly intentional. The other error seems to be string corruption, as I was running an experiment on seperating modded game saves and regular saves. For now, try creating a copy of SAVE_DATA and paste it in My Games, renaming it "EDF4.1_MODSAVES", and see if it can load them. I will investigate any additional problems related to the strapper as soon as possible.

**Comment by FIRE-AKA-DRAZN** [comment]
that appears to have resolved it.  

For clarity, the MAINSCRIPT.AS and COMMONTYPES.H need to be in the SgottMods folder to work.

For saves, you must go inside your EDF4.1 save folder found in My Documents/My Games and copy the folder SAVE_DATA and paste it in your My Games folder, after which you need to rename it EDF4.1_MODSAVES

Though the game displays a blank message with an OK button, after confirming it will load correctly and is playable.
